export const Projectsdata = [
    {
      category: 'Road Works',
      projects: [
        {
          id: 1,
          title: 'Performance Base Routine Maintenance of Lot 13 Roads Lavington Area',
          client: 'KURA (NBI)',
          value: '27,432,573.20 KSHS',
          role: 'Prime Contractor',
          year: '2016',
        },
        {
          id: 2,
          title: 'Routine Maintenance of Lot 5 Lusaka Road in Bungoma Municipality',
          client: 'KURA (Western)',
          value: '12,666,040.00 KSHS',
          role: 'Prime Contractor',
          year: 'May 2017',
        },
        {
          id: 3,
          title: 'Performance Based Routine Maintenance of Lot 4 Roads in Nrb.',
          client: 'KURA (NBI)',
          value: '31,592,982.80 KSHS',
          role: 'Prime Contractor',
          year: 'Sept. 2017',
        },
        {
          id: 4,
          title: 'Periodic Maintenance',
          client: 'KURA (NBI)',
          value: '80,011,779.52 KSHS',
          role: 'Prime Contractor',
          year: 'May 2018',
        },
        {
          id: 5,
          title: 'Routine Maintenance of Lot 7 Roads Chuka Municipality',
          client: 'KURA (UPPER Eastern)',
          value: '23,824,428.00 KSHS',
          role: 'Prime Contractor',
          year: 'Feb. 2018',
        },
        {
          id: 6,
          title: 'Mitunguu Tarmac B6 Link Road Paving works Phase 1',
          client: 'County Government of Meru',
          value: '10,558,755.00 KSHS',
          role: 'Prime Contractor',
          year: 'Oct. 2018',
        },
        {
          id: 7,
          title: 'Mitunguu Tarmac B6 Link Road Paving Works Phase 2',
          client: 'County Government of Meru',
          value: '8,959,567.00 KSHS',
          role: 'Prime Contractor',
          year: 'Oct. 2018',
        },
        {
          id: 8,
          title: 'Rehabilitation of Kapenguria Road',
          client: 'KURA (Nairobi)',
          value: '39,937,640.00 KSHS',
          role: 'Prime Contractor',
          year: '2019',
        },
        {
          id: 9,
          title: 'Upgrading of Mati-Nkabune Technical Institute Road to Paved Standards in Imenti North Ward',
          client: 'County Government of Meru',
          value: '14,992,176.13 KSHS',
          role: 'Prime Contractor',
          year: '2020',
        },
        {
          id: 10,
          title: 'Construction of Gatimene Kienderu Road Meru County',
          client: 'KURA (Meru)',
          value: '72,313,008.00 KSHS',
          role: 'Prime Contractor',
          year: '2021',
        },
        {
          id: 11,
          title: 'Up-grading of Kombe Road To Bitumen (Baobab Estate Karen) Standards',
          client: 'KURA (Nairobi)',
          value: '74,660,902.00 KSHS',
          role: 'Prime Contractor',
          year: '2021',
        },
        {
          id: 12,
          title: 'Proposed Grading And Murraming Enkasiti–Birika Road In Kitengela Ward',
          client: 'Kajiado County Government',
          value: '9,006,240.00 KSHS',
          role: 'Prime Contractor',
          year: '2023',
        },
        {
          id: 13,
          title: 'Routine and Periodic maintenance of Embu Town Roads-Lot 1',
          client: 'KURA (HQ)',
          value: '80,973,800.00 KSHS',
          role: 'Prime Contractor',
          year: '2023',
        },
      ],
    },
    {
      category: 'Building Works',
      projects: [
        {
          id: 1,
          title: 'Proposed Renovation of Kaelo Dispensary',
          client: 'County Government of Meru',
          value: '2,715,848.00 KSHS',
          role: 'Prime Contractor',
          year: 'June 2019',
        },
        {
          id: 2,
          title: 'Proposed Ward Completion and Face-lifting of Kangeta Sub-county Hospital',
          client: 'County Government of Meru',
          value: '3,930,900.00 KSHS',
          role: 'Prime Contractor',
          year: 'May 2019',
        },
        {
          id: 3,
          title: 'Upgrading of Kianjai Open Air Market to Paved Standards & Associated Works',
          client: 'County Government of Meru',
          value: '52,492,125.55 KSHS',
          role: 'Sub-Contractor',
          year: '2020',
        },
        {
          id: 4,
          title: 'Construction of Thimangu Plaza',
          client: 'Julius Thimangu',
          value: '48,369,000.00 KSHS',
          role: 'Prime Contractor',
          year: 'Ongoing',
        },
      ],
    },
    {
      category: 'Water Works',
      projects: [
        {
          id: 1,
          title: 'Borehole Drilling at Petals Of Africa School Ngochoni',
          client: 'Petals Of Africa School',
          value: '2,450,150.00 KSHS',
          role: 'Prime Contractor',
          year: '2021',
        },
        {
          id: 2,
          title: 'Kikuyu Water and Sewerage Project',
          client: 'Nanchang Municipal Engineering Dev.Group',
          value: '4,919,100.00 KSHS',
          role: 'Prime Contractor',
          year: '2021',
        },
        {
          id: 3,
          title: 'Borehole Drilling for Daniel Ketoto Ounda',
          client: 'Daniel Ketoto Ounda',
          value: '2,415,000.00 KSHS',
          role: 'Prime Contractor',
          year: '2021',
        },
        {
          id: 4,
          title: 'Drilling, pump installation and equipping of boreholes at Marsabit Stadium in Marsabit County',
          client: 'Benisa Limited',
          value: '7,563,940.00 KSHS',
          role: 'Prime Contractor',
          year: '2021',
        },
        {
          id: 5,
          title: 'Proposed Drilling And Equipping Of Mosiro Health Borehole In Mosiro Ward',
          client: 'Kajiado County Government',
          value: '6,988,843.40 KSHS',
          role: 'Prime Contractor',
          year: '2023',
        },
        {
          id: 6,
          title: 'Borehole Drilling and Equipping in Murang’a',
          client: 'Panviva Limited',
          value: '2,763,930.00 KSHS',
          role: 'Sub-Contractor',
          year: '2023',
        },
        {
          id: 7,
          title: 'Borehole Drilling and Equipping in Machakos',
          client: 'Kinematics Construction Company',
          value: '2,626,000.00 KSHS',
          role: 'Prime Contractor',
          year: '2023',
        },
        {
          id: 8,
          title: 'Borehole Drilling and Equipping in Mitunguu',
          client: 'Arichem Limited',
          value: '1,029,546.40 KSHS',
          role: 'Prime Contractor',
          year: '2023',
        },
        {
          id: 9,
          title: 'Borehole Drilling and Equipping in Siakago',
          client: 'Edward Kigoro',
          value: '2,756,000.00 KSHS',
          role: 'Prime Contractor',
          year: '2023',
        },
        {
          id: 10,
          title: 'Borehole Drilling and Equipping in Nchiru',
          client: 'Josphat Kinyua',
          value: '2,925,000.00 KSHS',
          role: 'Prime Contractor',
          year: '2023',
        },
      ],
    },
  ];
  